### PR TITLE
Presentation slides for yesterday's presentation

### PR DESCRIPTION
**Pull request by MitjaNemec**
@romunov Here they are. I'll delete my fork of the repo in a couple of weeks, so please store the slides somewhere else.

thanks for the organization.

### CODE REVIEW

**Comment by romunov** [comment]
Your presentation should be included in #32. Thank you for your cooperation.

**Comment by romunov** [comment]
@MitjaNemec would you consider sharing your presentation via https://speakerdeck.com/ ? See #32 for some discussion on the topic.

**Comment by MitjaNemec** [comment]
Available at: https://speakerdeck.com/mitjan/my-journey-as-a-python-plugin-developer-for-kicad

**Comment by romunov** [comment]
Thanks, much appreciated!

**Pull request closed without merging**
